[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "It counts things. Amazing!"
authors = [{name = "Miki Rosario", email = "mrosario@student.42madrid.com"}]
license = { file = "LICENSE" }
